module.exports = {
  USER_ADMIN: "Administrator",
  USER_STAFF: "Staff",
  USER_SUPERVISOR: "Supervisor",
  USER_OWNER: "Owner",
  RM_CATEGORY: "RM_CATEGORY",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  PAYMENT_TYPE_CASH: "Cash",
  PAYMENT_TYPE_CREDIT_CARD: "Credit Card",
  OPENING_TIME: "opening_time",
  CLOSING_TIME: "closing_time",
  DISPATCH_UNIT_IP: "dispatch_unit_ip",
  MARKUP_OPTION_ADD_ON_VALUE: "ADD-ON VALUE",
  MARKUP_OPTION_PERCENT_ADD_ON: "PERCENT ADD-ON",
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
  SALES_MODEL: "sales",
  SALES_OTHER_SET_MODEL: "sales_other_sets",
  PO_STATUS_ACCOMPLISHED: "Accomplished",
  PO_STATUS_PENDING: "Pending",
  PO_STATUS_PARTIAL: "Partial",
  PO_STATUS_CLOSED: "Closed",
  APPROVED: "Approved",
  SENIOR_DISC_RATIO: "VAT EXEMPTED AND 20% DISC RATIO",
  THERMAL_LINE_MAX_CHAR: 48,
  DISPATCH_UNIT_IP: "dispatch_unit_ip",
  OPEN: "Open",
  CLOSED: "Closed",
  CANCELLED: "Cancelled",
  UNBUNDLED: "Unbundled",
  BUNDLED: "Bundled",
  SETTING_MAIN_WAREHOUSE: "main_warehouse",
  SETTING_STORE: "store",
  SETTING_RECEIPT_FOOTER: "receipt_footer",
  FINALIZED: "Finalized",
  DELIVERY_TYPE_COMPANY_DELIVERED: "Company Delivered",
  DELIVERY_TYPE_OWN_DELIVERY: "Own Delivery",
  DELIVERY_TYPE_DELIVERED_BY_SUPPLIER: "Delivered by Supplier",
  DELIVERY_TYPE_PICKUP_DEPOT: "Pickup-Depot",
  STATUS_PARTIAL: "Partial",
  STATUS_FULL: "Full",
  SOURCE_DEPOT: "Tank Farm",
  SOURCE_SUPPLIER: "Depot",
  SOURCE_SUPPLIER_DEPOT: "Supplier/Depot",
  STATUS_PAID: "Paid",
  CREDIT_MEMO_UNCLAIMED: "Unclaimed",
  CREDIT_MEMO_CLAIMED: "Claimed",
  CREDIT_MEMO_PARTIALLY_CLAIMED: "Partially Claimed",
  STATUS_ALLOW_PRICE_EDIT: "Allow Price Edit",
  STATUS_PAID: "PAID",

  MODULE_WAREHOUSE_RECEIPT: "Warehouse Receipt",
  MODULE_DISPLAY_DELIVERY_RECEIPTS: "Display Delivery Receipts",
  MODULE_STOCK_TRANSFER: "Stock Transfer",
  MODULE_CASH_SALES: "Cash Sales",
  MODULE_CHARGE_SALES: "Charge Sales",
  MODULE_PURCHASE_RETURNS: "Purchase Returns",
  MODULE_RETURN_STOCK: "Return Stock",
  MODULE_CREDIT_MEMO: "Credit Memo",
  MODULE_INVENTORY_ADJUSTMENTS: "Inventory Adjustments",

  ACTION_SAVE: "Save",
  ACTION_UPDATE: "Update",
  ACTION_APPROVE: "Approve",
  ACTION_CANCEL: "Cancel",
  ACTION_PRINT: "Print",
  ACTION_BACKUP: "Backup",
  ACTION_BACKUP_RESTORE: "Backup Restore",
  PAYMENT_TYPE_CASH: "Cash",
  PAYMENT_TYPE_CHARGE: "Charge",
};
