const mongoose = require("mongoose");
const AccountGroupModel = require("./AccountGroupModel");
const BankModel = require("./BankModel");
const BranchModel = require("./BranchModel");

module.exports = {
  _id: mongoose.Schema.Types.ObjectId,
  account_id: Number,
  account_code: String,
  account: String,
  date_birth: Date,
  civil_status: String,
  address: String,
  telno: String,
  sss: String,
  account_group: {
    _id: mongoose.Schema.Types.ObjectId,
    name: String,
    account_group_id: Number,
    sgroup: String,
    account_group_type: String,
  },
  branch: {
    ...BranchModel,
    _id: mongoose.Schema.Types.ObjectId,
  },
  account_status: String,

  bank: {
    ...BankModel,
    _id: mongoose.Schema.Types.ObjectId,
  },

  bank_account: String,
  salary: Number,
  salary_pawned: Number,
  salary_excess: Number,
  term: Number,
  bank_cardno: String,
  date_atm_in: Date,
  date_atm_out: Date,
  bank_pin: Number,
  withdraw_day: Number,
  office: String,
  ofc_telno: String,
  ofc_address: String,
  remarks: String,
  date_loan: Date,
  comaker1: String,
  date_birth_com1: Date,
  comaker1_address: String,
  comaker2: String,
  date_birth_com2: Date,
  comaker2_address: String,
  comaker3: String,
  date_birth_com3: Date,
  comaker3_address: String,
  spouse: String,
  date_wifey: Date,
  benefit1: String,
  date_birthb1: Date,
  benefit1_address: String,
  benefit2: String,
  date_birthb2: Date,
  benefit2_address: String,
  benefit3: String,
  date_birthb3: Date,
  benefit3_address: String,
  type: {
    type: String,
  },
  collection_type: {
    collection_type_id: Number,
    name: String,
    _id: mongoose.Schema.Types.ObjectId,
  },
  claim_type: {
    claim_type_id: Number,
    name: String,
    _id: mongoose.Schema.Types.ObjectId,
  },
  date_expiry: Date,
  spmos: String,
  division: String,
  relate1: String,
  relate2: String,
  branch_manager: {
    staff_id: Number,
    name: String,
    staff_code: String,
    class: String,
    branch: {
      ...BranchModel,
      _id: mongoose.Schema.Types.ObjectId,
    },
    _id: mongoose.Schema.Types.ObjectId,
  },
  sales_consultant: {
    staff_id: Number,
    name: String,
    staff_code: String,
    class: String,
    branch: {
      ...BranchModel,
      _id: mongoose.Schema.Types.ObjectId,
    },
    _id: mongoose.Schema.Types.ObjectId,
  },
  relateb1: String,
  relateb2: String,
  relateb3: String,
  kandado: Number,
  relate3: String,
  pension: Number,
  totalpension: Number,
  bank_branch: String,
  date_spend: Date,
  date_mature1: Date,
  date_mature2: Date,
  date_mature3: Date,
  tdate: Date,
  area: {
    name: String,
    area_code: String,
    enable: String,
    subarea: String,
    _id: mongoose.Schema.Types.ObjectId,
  },
  withdraw_day2: Number,
  bank2: {
    ...BankModel,
    _id: mongoose.Schema.Types.ObjectId,
  },
  startyear: Number,
};
